# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cabildeas
email: your-email@domain.com
description: "La plataforma de Populusaurio con ideas de la sociedad civil para las conversaciones sobre la Nueva Constituci√≥n http://cabildeas.cl/"
baseurl: "" # the subpath of your site, e.g. /blog
basedomain: cabildeas.cl
twitter: procesoconstituyente
analytics: "UA-76464035-2"

# Build settings
markdown: kramdown
